name: online_shop
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #flutter_native_splash:
  flutter_native_splash: ^2.4.6

  #lottie:
  lottie: ^3.3.1

  #smooth_page_indicator:
  smooth_page_indicator: ^1.2.1

  #getX package :
  get: ^4.7.2

  #get_storage:
  get_storage: ^2.1.1

  #icons_launcher:
  iconsax: ^0.0.8

  #carousel_slider:
  carousel_slider: ^5.1.1

  #cached_network_image:
  cached_network_image: ^3.4.1

  #readmore:
  readmore: ^3.0.0

  #firebase_core:
  firebase_core: ^4.1.0

  #firebase_auth:
  firebase_auth: ^6.0.2

  #cloud_firestore:
  cloud_firestore: ^6.0.1

  #google_sign_in:
  google_sign_in: ^6.2.1

  #http:
  http: ^1.5.0

  #connectivity_plus:
  connectivity_plus: ^6.1.5

  #shimmer:flj
  shimmer: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/logo/
    - assets/fonts/
    - assets/animations/
    - assets/image/
    - assets/icons/categories/
    - assets/banners/
    - assets/products/
    - assets/brands/
    - assets/icons/payment_methods/


  fonts:
    - family: "Nunito"
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300

        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 800

        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic

        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500

        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400

        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Nunito-MediumItalic.ttf
          weight: 500
          style: italic