// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKnW6_B7C9Nv2Cc_FFQqiecCE3Pf8PrSs',
    appId: '1:576934019579:web:523e69ee20ec316ab5cb5e',
    messagingSenderId: '576934019579',
    projectId: 'onlinestore-5b4f8',
    authDomain: 'onlinestore-5b4f8.firebaseapp.com',
    storageBucket: 'onlinestore-5b4f8.firebasestorage.app',
    measurementId: 'G-9S4S4NTM0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJugv0Co9CrPPUOqDcO6pZlzL8w_ajmhc',
    appId: '1:576934019579:android:fc135ff69393f54db5cb5e',
    messagingSenderId: '576934019579',
    projectId: 'onlinestore-5b4f8',
    storageBucket: 'onlinestore-5b4f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgQeKEytdCCdG770FZwcjP7KQvMjcakz4',
    appId: '1:576934019579:ios:1814d6add60f4092b5cb5e',
    messagingSenderId: '576934019579',
    projectId: 'onlinestore-5b4f8',
    storageBucket: 'onlinestore-5b4f8.firebasestorage.app',
    androidClientId: '576934019579-jm0b8oaugigscph0h1u4eugfsfbeqtm4.apps.googleusercontent.com',
    iosClientId: '576934019579-jpfqd3pqaf7if7dkp68d02n0493tqiu8.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineShopping',
  );

}